package com.koinonia.igreja.presentation.features.members

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.koinonia.igreja.data.local.dao.MemberDao
import com.koinonia.igreja.data.local.entity.MemberEntity
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import java.util.Date
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class MemberListViewModel @Inject constructor(
    private val memberDao: MemberDao
) : ViewModel() {
    val membersList: Flow<List<MemberEntity>> = memberDao.getAllMembers()

    init {
        seedDatabaseIfNeeded()
    }

    private fun seedDatabaseIfNeeded() {
        viewModelScope.launch {
            try {
                val current = membersList.first()
                if (current.isEmpty()) {
                    val seedMembers = listOf(
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "João da Silva",
                            photoUrl = null,
                            birthDate = Date(80, 5, 12), // 1980
                            cep = "40000000",
                            street = "Avenida Sete de Setembro",
                            number = "100",
                            neighborhood = "Centro",
                            city = "Salvador",
                            state = "BA",
                            complement = "Apto 101",
                            phone = "71988887777",
                            isWhatsapp = true,
                            socialMedia = "joaosilva",
                            civilStatus = "Casado(a)",
                            baptismDate = Date(100, 10, 20),
                            rebaptismDate = null,
                            rg = "123456789",
                            cpf = "12345678901",
                            spouseId = null,
                            spouseName = "Maria Santos Souza",
                            hasVehicle = true,
                            vehicleType = "CARRO",
                            vehicleModel = "Toyota Corolla",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Maria Santos Souza",
                            photoUrl = null,
                            birthDate = Date(85, 3, 22),
                            cep = "40100000",
                            street = "Rua Barão de Itapoan",
                            number = "45",
                            neighborhood = "Barra",
                            city = "Salvador",
                            state = "BA",
                            complement = "Casa",
                            phone = "71999998888",
                            isWhatsapp = true,
                            socialMedia = "mariadesouza",
                            civilStatus = "Casado(a)",
                            baptismDate = Date(105, 8, 15),
                            rebaptismDate = null,
                            rg = "987654321",
                            cpf = "98765432109",
                            spouseId = null,
                            spouseName = "João da Silva",
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Carlos Eduardo Lima",
                            photoUrl = null,
                            birthDate = Date(92, 11, 5),
                            cep = "40200000",
                            street = "Rua Waldemar Falcão",
                            number = "321",
                            neighborhood = "Horto Florestal",
                            city = "Salvador",
                            state = "BA",
                            complement = "Edf. Horto, Apto 502",
                            phone = "71977776666",
                            isWhatsapp = false,
                            socialMedia = "carlosedu",
                            civilStatus = "Solteiro(a)",
                            baptismDate = Date(112, 4, 12),
                            rebaptismDate = null,
                            rg = "456789123",
                            cpf = "45678912301",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = true,
                            vehicleType = "MOTO",
                            vehicleModel = "Honda CB 500",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Ana Júlia Pinheiro",
                            photoUrl = null,
                            birthDate = Date(98, 1, 30),
                            cep = "40300000",
                            street = "Rua Direita de Santo Antônio",
                            number = "12",
                            neighborhood = "Santo Antônio",
                            city = "Salvador",
                            state = "BA",
                            complement = null,
                            phone = "71966665555",
                            isWhatsapp = true,
                            socialMedia = "anajulia_p",
                            civilStatus = "Solteiro(a)",
                            baptismDate = Date(118, 9, 21), // Batizada
                            rebaptismDate = null,
                            rg = "321654987",
                            cpf = "32165498701",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Pedro Alencar Castro",
                            photoUrl = null,
                            birthDate = Date(75, 7, 18),
                            cep = "40400000",
                            street = "Rua da Paciência",
                            number = "88",
                            neighborhood = "Rio Vermelho",
                            city = "Salvador",
                            state = "BA",
                            complement = "Apto 204",
                            phone = "71955554444",
                            isWhatsapp = true,
                            socialMedia = "pedro_alencar",
                            civilStatus = "Divorciado(a)",
                            baptismDate = Date(95, 6, 25),
                            rebaptismDate = null,
                            rg = "789123456",
                            cpf = "78912345601",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = true,
                            vehicleType = "CARRO",
                            vehicleModel = "Ford Ka",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Fernanda Ribeiro Lima",
                            photoUrl = null,
                            birthDate = Date(88, 9, 14),
                            cep = "40000000",
                            street = "Avenida Centenário",
                            number = "1500",
                            neighborhood = "Chame-Chame",
                            city = "Salvador",
                            state = "BA",
                            complement = "Edf. Centenário, Apto 1201",
                            phone = "71944443333",
                            isWhatsapp = true,
                            socialMedia = "fernanda_rl",
                            civilStatus = "Casado(a)",
                            baptismDate = Date(110, 2, 28),
                            rebaptismDate = null,
                            rg = "654987321",
                            cpf = "65498732101",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Lucas Mateus Oliveira",
                            photoUrl = null,
                            birthDate = Date(95, 4, 3),
                            cep = "41000000",
                            street = "Avenida Manoel Dias da Silva",
                            number = "900",
                            neighborhood = "Pituba",
                            city = "Salvador",
                            state = "BA",
                            complement = "Sala 4",
                            phone = "71933332222",
                            isWhatsapp = false,
                            socialMedia = "lucasmateus",
                            civilStatus = "Solteiro(a)",
                            baptismDate = Date(115, 12, 10),
                            rebaptismDate = null,
                            rg = "951753852",
                            cpf = "95175385201",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = true,
                            vehicleType = "MOTO",
                            vehicleModel = "Yamaha Fazer 250",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Beatriz Rocha Gomes",
                            photoUrl = null,
                            birthDate = Date(90, 6, 27),
                            cep = "41200000",
                            street = "Rua do Cabral",
                            number = "54",
                            neighborhood = "Nazaré",
                            city = "Salvador",
                            state = "BA",
                            complement = "Casa B",
                            phone = "71922221111",
                            isWhatsapp = true,
                            socialMedia = "biarocha",
                            civilStatus = "Solteiro(a)",
                            baptismDate = Date(108, 5, 17),
                            rebaptismDate = null,
                            rg = "852963741",
                            cpf = "85296374101",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Marcos Vinícius Andrade",
                            photoUrl = null,
                            birthDate = Date(82, 0, 11),
                            cep = "41300000",
                            street = "Rua Silveira Martins",
                            number = "1042",
                            neighborhood = "Cabula",
                            city = "Salvador",
                            state = "BA",
                            complement = "Apto 303B",
                            phone = "71911110000",
                            isWhatsapp = true,
                            socialMedia = "marcos_vinicius",
                            civilStatus = "Casado(a)",
                            baptismDate = Date(102, 11, 8),
                            rebaptismDate = null,
                            rg = "741852963",
                            cpf = "74185296301",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = true,
                            vehicleType = "CARRO",
                            vehicleModel = "Chevrolet Onix",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Juliana Mendes Ferreira",
                            photoUrl = null,
                            birthDate = Date(87, 8, 19),
                            cep = "41700000",
                            street = "Avenida Octávio Mangabeira",
                            number = "3400",
                            neighborhood = "Armação",
                            city = "Salvador",
                            state = "BA",
                            complement = "Casa 10",
                            phone = "71999887766",
                            isWhatsapp = true,
                            socialMedia = "ju_mendes",
                            civilStatus = "União Estável",
                            baptismDate = Date(107, 7, 24),
                            rebaptismDate = null,
                            rg = "963852741",
                            cpf = "96385274101",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Felipe Gabriel Cunha",
                            photoUrl = null,
                            birthDate = Date(94, 2, 8),
                            cep = "41800000",
                            street = "Rua Rubem Berta",
                            number = "77",
                            neighborhood = "Itaigara",
                            city = "Salvador",
                            state = "BA",
                            complement = "Apto 801",
                            phone = "71999776655",
                            isWhatsapp = false,
                            socialMedia = "felipe_cunha",
                            civilStatus = "Solteiro(a)",
                            baptismDate = Date(114, 1, 14),
                            rebaptismDate = null,
                            rg = "159357258",
                            cpf = "15935725801",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = true,
                            vehicleType = "CARRO",
                            vehicleModel = "Hyundai HB20",
                            syncPending = false
                        ),
                        MemberEntity(
                            id = UUID.randomUUID().toString(),
                            familyId = null,
                            fullName = "Camila Nogueira Neves",
                            photoUrl = null,
                            birthDate = Date(91, 10, 15),
                            cep = "41900000",
                            street = "Rua Oswaldo Cruz",
                            number = "250",
                            neighborhood = "Rio Vermelho",
                            city = "Salvador",
                            state = "BA",
                            complement = "Edf. Mar, Apto 202",
                            phone = "71999665544",
                            isWhatsapp = true,
                            socialMedia = "camila_nogueira",
                            civilStatus = "Viúvo(a)",
                            baptismDate = Date(111, 10, 9),
                            rebaptismDate = null,
                            rg = "753159258",
                            cpf = "75315925801",
                            spouseId = null,
                            spouseName = null,
                            hasVehicle = false,
                            vehicleType = null,
                            vehicleModel = null,
                            syncPending = false
                        )
                    )
                    memberDao.insertMembers(seedMembers)
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }
}
